### ISSUE TITLE
Documentation of data layout

### ISSUE THREAD

**Issue by danpovey** [WarrenWeckesser/wavio#10]
It would be nice to have documentation at this point of the data layout (e.g. is the shape (channels, samples) or vice versa?) . and the numpy dtype.

https://github.com/WarrenWeckesser/wavio/blob/5c6c9103f8c7b3318798f1aba15d2aa56d89e9de/wavio.py#L108

**Comment by WarrenWeckesser** [comment]
Good idea.  I just pushed a commit with expanded descriptions of the attributes of the Wav object.
