### ISSUE TITLE
TypeError: cannot unpack non-iterable Wav object

### ISSUE THREAD

**Issue by saumyaborwankar** [WarrenWeckesser/wavio#14]
Simply calling the read function on a wav file returns this error

**Comment by WarrenWeckesser** [comment]
Can you post a [minimal, reproducible example], including the relevant WAV file, so I can try to reproduce the result?

**Comment by saumyaborwankar** [comment]
rate,signal1.b=wavio.read('/home/crazypikachu/Desktop/dataForEnvironmentPaper/UrbanSound8K/audio/fold1/101415-3-0-2.wav')
Traceback (most recent call last):

  File "<ipython-input-48-30c4ccfd489d>", line 1, in <module>
    rate,signal1.b=wavio.read('/home/crazypikachu/Desktop/dataForEnvironmentPaper/UrbanSound8K/audio/fold1/101415-3-0-2.wav')

TypeError: cannot unpack non-iterable Wav object

**Comment by saumyaborwankar** [comment]
rate,signal1.b=wavio.read('/home/crazypikachu/Desktop/7061-6-0-0.wav')
Traceback (most recent call last):

  File "<ipython-input-49-8a170d0f6327>", line 1, in <module>
    rate,signal1.b=wavio.read('/home/crazypikachu/Desktop/7061-6-0-0.wav')

TypeError: cannot unpack non-iterable Wav object

Heres the link to the wav file: https://drive.google.com/file/d/1V6lV7CgcvTJSEM3P4xlmzGC4BgdKOIls/view?usp=sharing

**Comment by WarrenWeckesser** [comment]
`wavio.read` returns a single object, so you can't unpack it.  Instead, do somethining like

    wav = wavio.read('/home/crazypikachu/Desktop/7061-6-0-0.wav')

and then access `wav.rate`, `wav.data` and `wav.sampwidth` as needed.

There is an example of this in the `wavio.read` docstring:

```
>>> wav = wavio.read('test.wav')
>>> wav.rate
22050
>>> wav.sampwidth
1
>>> wav.data
array([[ 0],
       [ 5],
       [10],
       [15],
       [20],
       [20],
       [10],
       [25]], dtype=uint8)
```
