### ISSUE TITLE
How to write a file using fractional seconds

### ISSUE THREAD

**Issue by brno32** [WarrenWeckesser/wavio#18]
The `README` says

```
and it does not handle floating point WAV files. (When floating point data is passed to wavio.write it is converted to integers before being written to the WAV file.)
```

so that does mean it's not possible to support fractional seconds? e.g., can I make a file using this library that's 1.3 seconds long?

**Comment by WarrenWeckesser** [comment]
That comment refers to the values in each sample.  The time resolution is determined by the sample rate, so to get a file that is 1.3 seconds long with a sample rate of, say 44100 samples/sec, you would create 44100*1.3 = 57330 samples.

**Comment by WarrenWeckesser** [comment]
I'm closing the issue.  Further comments are welcome if there are still any questions.
