### ISSUE TITLE
wavio import is failing

### ISSUE THREAD

**Issue by superingram** [WarrenWeckesser/wavio#19]
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File ["<ipython-input-10-03e565a7f4cd>"](https://localhost:8080/#), line 1, in <module>
    import wavio

  File "<fstring>", line 1
    (scale=)
          ^
SyntaxError: invalid syntax

**Comment by superingram** [comment]
This is happening upon using "import wavio", any ideas when this will be resolved?

**Comment by WarrenWeckesser** [comment]
I can't reproduce this.  How did you install `wavio`?  The error message refers to IPython.  Are you running `import wavio` from within an IDE or editor?  If you run a plain python shell in a terminal (i.e. open up a terminal and enter `python`) and then execute `import wavio`, do you get the same error?

**Comment by WarrenWeckesser** [comment]
Thanks for reporting the issue @superingram.  The code has been fixed, and the fixed version (0.0.7) has been released on PyPI.
