### ISSUE TITLE
PyPI?

### ISSUE THREAD

**Issue by TC01** [WarrenWeckesser/wavio#2]
Would it be possible for this module to be added to PyPI?

**Comment by WarrenWeckesser** [comment]
Sure, just give me a few days to figure out the details.  Thanks for your interest!

**Comment by WarrenWeckesser** [comment]
Well, "a few days" turned into "a few weeks", but here it is: https://pypi.python.org/pypi/wavio

Note that the API has changed in 0.0.2.  The functions are `wavio.read()` and `wavio.write()`.  `wavio.read()` returns an object with `data`, `rate` and `sampwidth` attributes.  `wavio.write()` behaves differently and has more options than the old `writewav24()`.
