### ISSUE TITLE
Code typo

### ISSUE THREAD

**Issue by JoelSjogren** [WarrenWeckesser/wavio#3]
data = _np.zeros(data.shape, dtyp=dt)

Should be dtype, not dtyp.

**Comment by WarrenWeckesser** [comment]
@JoelSjogren Thanks for reporting that problem!  I'll fix it ASAP.  (Shame on me for not having a appropriate unit test for that case.)

**Comment by WarrenWeckesser** [comment]
>  I'll fix it ASAP.

Finally fixed.  So much for "ASAP".  :flushed:
