### ISSUE TITLE
96 kHz 24 bit audio files not supported

### ISSUE THREAD

**Issue by audiofeature** [WarrenWeckesser/wavio#4]
I used wavio.py 0.0.1 for quite a while but just installed wavio-0.0.3 freshly via pip.

In both cases, on an 96 kHz 24 bit audio file I get the following error (0.0.3 in this case).

>>> from wavio import read
>>> Wav = read('000042B1-0005294207.wav')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/wavio.py", line 164, in read
    wav = _wave.open(file)
  File "/usr/lib/python2.7/wave.py", line 511, in open
    return Wave_read(f)
  File "/usr/lib/python2.7/wave.py", line 164, in __init__
    self.initfp(f)
  File "/usr/lib/python2.7/wave.py", line 144, in initfp
    self._read_fmt_chunk(chunk)
  File "/usr/lib/python2.7/wave.py", line 274, in _read_fmt_chunk
    raise Error, 'unknown format: %r' % (wFormatTag,)
wave.Error: unknown format: 65534

The linux 'file' command however correctly identifies the file format:

file 000042B1-0005294207.wav 
000042B1-0005294207.wav: RIFF (little-endian) data, WAVE audio, stereo 96000 Hz

Is 96 kHz / 24 bit audio format a doable thing?

**Comment by audiofeature** [comment]
Just realized the problem is in Pythons wave package and reported here
https://github.com/jiaaro/pydub/issues/129
and here
http://stackoverflow.com/questions/29000788/large-wave-file-not-being-read-in-python

saying:
Format 65534 is a format called WAVE_FORMAT_EXTENSIBLE defined by Microsoft and is used for multi-channel wave files. It's pretty uncommon. 

I guess I should close this issue as wont fix by wavio.

**Comment by WarrenWeckesser** [comment]
Thanks for tracking down the source of the problem.  `wavio` relies on the Python `wave` standard library, so if `wave` can't handle it, `wavio` also can't handle it.
