### ISSUE TITLE
RuntimeWarning: overflow encountered in short_scalars

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [WarrenWeckesser/wavio#5]
https://github.com/WarrenWeckesser/wavio/blob/3c63f3d434ec80290d65084f3d1155d4d641bdcb/wavio.py#L203

`vmax - vmin` results in an overflow because they are both near the max and min values of their integer.

**Comment by WarrenWeckesser** [comment]
@BebeSparkelSparkel, do you have an example that I can run to recreate the problem?

**Comment by BebeSparkelSparkel** [comment]
Read and then write this file with waveio
https://github.com/BebeSparkelSparkel/BeatBoxTranslator/blob/master/sample1.wav

**Comment by mbarkhau** [comment]
Just ran into this using the package on pypi. Is there a release on the horizon which includes this fix?

**Comment by BebeSparkelSparkel** [comment]
@mbarkhau if you want it now you can use this [install method](https://codeinthehole.com/tips/using-pip-and-requirementstxt-to-install-from-the-head-of-a-github-branch/). I'm not sure if @WarrenWeckesser has any plans on doing a release any time soon.

**Comment by WarrenWeckesser** [comment]
I just uploaded a new release to PiPY: https://pypi.org/project/wavio/
