### ISSUE TITLE
Question: Average amplitude of audio clip

### ISSUE THREAD

**Issue by alexhalford** [WarrenWeckesser/wavio#9]
Hi, I have a wav file, and I need a crude estimate of its average loudness (to measure ambient noise levels in a room). Does the following make sense:
```
s = wavio.read(file).data
mean_amplitude = numpy.mean(s)
```
or have I fundamentally misunderstood what wavio returns when it read a wav file?

**Comment by nikolai-kummer** [comment]
You are dealing with audio, which is generally sinusoidal. The average value of a sinusoid is 0 or a constant value.

You should look into the "root mean square value", rather than the average to determine loudness. That will likely be better suited for what you are trying to do.

**Comment by alexhalford** [comment]
Good point, ok, but if I use RMS, that should be fine?

**Comment by nikolai-kummer** [comment]
Yeah that should work. If it does not then there might be issues with the file that was loaded.
you can try running some error checks to make sure it was loaded properly:

`
clip = wavio.read(file)

length_in_seconds = len(clip.data)/clip.rate # length of loaded data in seconds
type(clip.data) #this should return numpy.ndarray

mean_amplitude = numpy.mean(clip.data) 
`

**Comment by alexhalford** [comment]
Yep, perfect. Had a bit of an issue with integer overflow, but got there in the end. Thank you!
